name: build and upload

on:
  push:
    branches:
      - main 

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
      - name: Build
        run: hugo --minify

      - name: Minio Deploy
        uses: mamal72/minio-perfect-deploy-action@main
        with:
          endpoint: minio.joeyh.dev
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: 'blog'
          source_dir: 'public'
          target_dir: '/'
