name: build and upload

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
      - name: Build
        run: hugo --minify

      - name: Minio Deploy
        env:
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
        run: |
          curl https://dl.min.io/client/mc/release/linux-amd64/mc --output mc
          chmod +x mc
          mc alias set deploy https://s3.joeyh.dev $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
          mc mirror --remove --overwrite public deploy/blog && mc anonymous set download deploy/blog
